using System.Linq;
using InscryptionAPI.Card;
using DiskCardGame;
using BepInEx.Bootstrap;
using System.Collections.Generic;
using System;
using UnityEngine;
using InscryptionAPI.Encounters;
using InscryptionAPI.Helpers;
using InscryptionAPI.Regions;
using Infiniscryption.PackManagement.UserInterface;
using HarmonyLib;
using System.Reflection;

namespace Infiniscryption.PackManagement
{
    [HarmonyPatch]
    public class EncounterPackInfo : PackInfoBase
    {
        internal EncounterPackInfo(bool isLeftovers) : base(isLeftovers) { }
        internal EncounterPackInfo(CardTemple temple) : base(temple)
        {
            // This is a cheat for the scrybe mods to allow the base game packs
            // to actually be defined the way the scrybe mods want
            if (temple == CardTemple.Tech)
                ModPrefix = "P03KCM";
            // TODO: Add similar hacks for grimora and magnificus
        }
        internal EncounterPackInfo(string cardPrefix, PackInfo.PackMetacategory category)
        {
            this.ModPrefix = cardPrefix;
            this.ValidFor = new() { category };
        }

        internal EncounterPackInfo(string cardPrefix)
        {
            this.ModPrefix = cardPrefix;
            string firstKey = this.PackContents.FirstOrDefault();
            if (string.IsNullOrEmpty(firstKey))
            {
                this.ValidFor = new() { PackInfo.PackMetacategory.LeshyPack };
            }
            else
            {
                var ebd = EncounterManager.AllEncountersCopy.FirstOrDefault(e => e.name.Equals(firstKey, StringComparison.InvariantCultureIgnoreCase));
                if (ebd == null)
                {
                    this.ValidFor = new() { PackInfo.PackMetacategory.LeshyPack };
                }
                else
                {
                    this.ValidFor = new() { PackInfo.GetTempleDefaultMetacategory(GetTemplesFromEncounter(ebd).First()) };
                }
            }
        }

        protected override void TryInitializeImpl()
        {
            List<string> encounters = Encounters.Select(e => e.name).ToList();
            List<string> regions = Regions.Select(e => e.name).ToList();
            if (encounters != null && encounters.Count > 0)
            {
                // Build the description
                AutoGeneratedDescription = $"Contains {encounters.Count} encounters.";

                // Build the title
                if (!String.IsNullOrEmpty(this.ModPrefix))
                {
                    try
                    {
                        PackInfo cardPack = PackManager.GetPackInfo(this.ModPrefix);
                        AutoGeneratedDescription = $"Contains {encounters.Count} encounters from {cardPack.Title}.";
                        AutoGeneratedTitle = $"Encounters Pack: {cardPack.Title}";
                        return;
                    }
                    catch { }
                }
                AutoGeneratedTitle = $"Encounters Pack: {this.ModPrefix}";
            }
        }

        // public List<string> AdditionalEncounters { get; set; } = new();

        // public List<string> AdditionalRegions { get; set; } = new();

        private static Dictionary<Color, Color> ReplacementColors = new()
        {
            { new Color(67f/256f, 70f/256f, 51f/256f), new Color(147f/256f,0f,0f) },
            { new Color(107f/256f, 113f/256f, 81f/256f), new Color(201f/256f,0f,0f) },
            { new Color(215f/256f, 226f/256f, 163f/256f), new Color(204f/256f,204f/256f,204f/256f) }
        };

        private static Color ReplaceColor(Color color)
        {
            foreach (var colors in ReplacementColors)
            {
                if (Mathf.Abs(color.r - colors.Key.r) < 0.05f &&
                    Mathf.Abs(color.g - colors.Key.g) < 0.05f &&
                    Mathf.Abs(color.b - colors.Key.b) < 0.05f)
                {
                    return colors.Value;
                }
            }
            return color;
        }

        private static Texture2D MakeEncounterSpriteFromPackSprite(Sprite target)
        {
            Texture2D origTex = TextureHelper.DuplicateTexture(target.texture);
            Texture2D retval = TextureHelper.GetImageAsTexture("default_encounter.png", typeof(EncounterPackInfo).Assembly);
            for (int x = 1; x < origTex.width - 1; x++)
                for (int y = 9; y < origTex.height - 7; y++)
                    retval.SetPixel(x, y - 1, ReplaceColor(origTex.GetPixel(x, y)));
            retval.Apply();
            return retval;
        }

        private Sprite _packArt;
        public override Sprite PackArt
        {
            get
            {
                if (_packArt != null)
                    return _packArt;

                if (!String.IsNullOrEmpty(this.ModPrefix))
                {
                    PackInfo info = PackManager.GetPackInfo(this.ModPrefix);
                    if (info.PackArt != null)
                    {
                        SetTexture(MakeEncounterSpriteFromPackSprite(info.PackArt));
                    }
                }
                else if (this.DefaultPackTemple.HasValue)
                {
                    PackInfo info = PackManager.GetDefaultPackInfo(this.DefaultPackTemple.Value);
                    if (info.PackArt != null)
                    {
                        SetTexture(MakeEncounterSpriteFromPackSprite(info.PackArt));
                    }
                }

                return _packArt;
            }
            protected set => _packArt = value;
        }

        public static CardTemple GetMostUniqueTempleFromEncounter(EncounterBlueprintData data)
        {
            List<CardTemple> temples = GetTemplesFromEncounter(data).Distinct().ToList();
            if (temples.Contains(CardTemple.Tech))
                return CardTemple.Tech;
            if (temples.Contains(CardTemple.Undead))
                return CardTemple.Undead;
            if (temples.Contains(CardTemple.Wizard))
                return CardTemple.Wizard;
            return CardTemple.Nature;
        }

        public static List<CardTemple> GetTemplesFromEncounter(EncounterBlueprintData data)
        {
            return data.turns.SelectMany(li => li.Where(cb => cb.card != null).Select(cb => cb.card.temple)).ToList();
        }

        public static Tuple<CardTemple, string> GetModPrefixesFromEncounter(EncounterBlueprintData data)
        {
            CardTemple temple = CardTemple.Nature;
            string prefix = string.Empty;
            foreach (var card in data.turns.SelectMany(li => li.Where(db => db.card != null).Select(db => db.card)))
            {
                temple = card.temple;
                if (!card.IsBaseGameCard())
                {
                    prefix = card.GetModPrefix();
                    break;
                }
            }
            if (string.IsNullOrEmpty(prefix))
            {
                foreach (var card in data.turns.SelectMany(li => li.Where(db => db.replacement != null).Select(db => db.replacement)))
                {
                    temple = card.temple;
                    if (!card.IsBaseGameCard())
                    {
                        prefix = card.GetModPrefix();
                        break;
                    }
                }
            }
            return new(temple, prefix);
        }

        private bool RegionIsValid(RegionData data)
        {
            // if (AdditionalRegions.Contains(data.name))
            //     return true;

            if (!string.IsNullOrEmpty(ModPrefix))
            {
                if (data.name.StartsWith($"{ModPrefix}_"))
                    return true;

                var region = RegionManager.NewRegions.FirstOrDefault(p1r => p1r.Region.name.Equals(data.name));
                if (region != null && region.GUID.Equals(ModPrefix, StringComparison.InvariantCultureIgnoreCase))
                    return true;
            }

            return false;
        }

        private bool EncounterIsValid(EncounterBlueprintData data)
        {
            // if (AdditionalEncounters.Contains(data.name))
            //     return true;

            if (!string.IsNullOrEmpty(ModPrefix))
            {
                if (data.name.StartsWith($"{ModPrefix}_"))
                    return true;

                if (EncounterMap.ContainsKey(data.name) && EncounterMap[data.name].Equals(ModPrefix, StringComparison.InvariantCultureIgnoreCase))
                    return true;
            }

            string prefix = data.name.Split('_')[0];
            if (PackManager.AllPacks<EncounterPackInfo>().Any(epi => !string.IsNullOrEmpty(epi.ModPrefix) && epi.ModPrefix.Equals(prefix, StringComparison.InvariantCultureIgnoreCase)))
                return false;

            if (!string.IsNullOrEmpty(ModPrefix) && GetModPrefixesFromEncounter(data).Item2.Equals(ModPrefix, StringComparison.InvariantCultureIgnoreCase))
                return true;

            return false;
        }

        public IEnumerable<RegionData> Regions
        {
            get
            {
                if (DefaultPackTemple.HasValue && DefaultPackTemple.Value == CardTemple.Nature)
                {
                    return RegionManager.AllRegionsCopy.Where(r => r.IsBaseGameRegion());
                }
                if (!String.IsNullOrEmpty(ModPrefix))
                {
                    return RegionManager.AllRegionsCopy.Where(r => !r.IsBaseGameRegion()).Where(RegionIsValid);
                }
                if (IsLeftoversPack)
                {
                    List<string> allKnownRegions = PackManager.AllPacks<EncounterPackInfo>().Where(pi => !pi.IsLeftoversPack).SelectMany(pi => pi.Regions).Select(r => r.name).ToList();
                    return RegionManager.AllRegionsCopy.Where(r => !r.IsBaseGameRegion()).Where(r => !allKnownRegions.Contains(r.name));
                }
                return new List<RegionData>();
            }
        }

        public IEnumerable<EncounterBlueprintData> Encounters
        {
            get
            {
                if (IsLeftoversPack)
                {
                    // Get all currently defined packs from the pack manager:
                    List<string> allPacked = PackManager.AllPacks<EncounterPackInfo>().Where(pi => !pi.IsLeftoversPack).SelectMany(pi => pi.Encounters).Select(e => e.name).ToList();
                    return EncounterManager.AllEncountersCopy.Where(r => !r.IsBaseGameEncounter()).Where(ebd => !allPacked.Contains(ebd.name));
                }

                if (DefaultPackTemple.HasValue && DefaultPackTemple.Value == CardTemple.Nature)
                    // Only the base game encounters for Leshy's cabin are valid
                    // All the scrybe modes do weird stuff so we can't actually use that definition
                    return EncounterManager.AllEncountersCopy.Where(ebd => ebd.IsBaseGameEncounter()).Where(ebd => GetTemplesFromEncounter(ebd).FirstOrDefault() == DefaultPackTemple.Value);
                else if (!String.IsNullOrEmpty(ModPrefix))
                    return EncounterManager.AllEncountersCopy.Where(ebd => !ebd.IsBaseGameEncounter()).Where(EncounterIsValid);

                return new List<EncounterBlueprintData>();
            }
        }

        public override IEnumerable<string> ScreenFilteredContents => IsBaseGameCardPack ? PackContents : Encounters.Where(e => GetTemplesFromEncounter(e).Contains(PackManager.ScreenState)).Select(e => e.name);

        public override IEnumerable<string> PackContents => Encounters.Select(e => e.name).Concat(Regions.Select(r => r.name));

        public override string Key
        {
            get
            {
                if (this.IsBaseGameCardPack)
                    return $"Encounter.{PackInfo.TEMPLEINDICATOR}{this.DefaultPackTemple.Value.ToString()}";

                if (this.IsLeftoversPack)
                    return $"Encounter.{PackInfo.LEFTOVERSINDICATOR}";

                return $"Encounter.M={this.ModPrefix}.C={this.ModPrefix}";
            }
        }

        public override CardInfo IconCard
        {
            get
            {
                List<string> contents = PackContents.ToList();
                var encounters = EncounterManager.AllEncountersCopy.Where(ebd => contents.Contains(ebd.name)).ToList();

                int maxPowerLevel = 0;
                CardInfo maxCard = null;

                foreach (var card in encounters.SelectMany(ebd => ebd.turns.SelectMany(cbl => cbl.Where(cb => cb.card != null).Select(cb => cb.card))))
                {
                    if (card.PowerLevel > maxPowerLevel)
                    {
                        maxPowerLevel = card.PowerLevel;
                        maxCard = card;
                    }
                }

                return maxCard;
            }
        }

        private static float CalcPowerLevel(EncounterBlueprintData data)
        {
            if (Mathf.Abs(data.PowerLevel) > 0.01f)
                return data.PowerLevel;

            try
            {
                return (float)data.turns.SelectMany(l => l.Where(cb => cb.card != null).Select(cb => cb.card.PowerLevel))
                    .Concat(data.turns.SelectMany(l => l.Where(cb => cb.replacement != null).Select(cb => cb.replacement.PowerLevel))).Average();
            }
            catch
            {
                return 0f;
            }
        }

        internal override bool SetOfPacksIsValid(List<PackInfoBase> packs, PackContentCache cache)
        {
            List<string> encounterNames = packs.Cast<EncounterPackInfo>().SelectMany(p => p.Encounters.Select(e => e.name)).ToList();
            List<string> regionNames = packs.Cast<EncounterPackInfo>().SelectMany(p => p.Regions.Select(e => e.name)).ToList();

            if (PackManager.ScreenState == CardTemple.Tech)
            {
                List<string> p03Regions = PackManager.GetDefaultPackInfo<EncounterPackInfo>(CardTemple.Tech).Regions.Select(r => r.name).Where(n => !n.ToLowerInvariant().Contains("mycologist")).ToList();
                regionNames.RemoveAll(r => !p03Regions.Contains(r));

                return RegionManager.AllRegionsCopy
                                    .Where(r => regionNames.Contains(r.name))
                                    .Select(r => r.encounters.Where(e => encounterNames.Contains(e.name)).Count())
                                    .Where(count => count == 0)
                                    .Count() == 0;
            }

            // We explicitly don't support these scrybes right now
            if (PackManager.ScreenState == CardTemple.Undead || PackManager.ScreenState == CardTemple.Wizard)
                return false;

            return RegionManager.AllRegionsCopy
                                .Where(r => regionNames.Contains(r.name))
                                .Select(r => r.encounters.Where(e => encounterNames.Contains(e.name)).Count())
                                .Where(count => count > 0)
                                .Count() >= 3;
        }

        public override float PowerLevel
        {
            get
            {
                var names = ScreenFilteredContents.ToList();
                try
                {
                    return (float)EncounterManager.AllEncountersCopy.Where(ci => names.Contains(ci.name)).Where(ci => ci != null).Select(CalcPowerLevel).Where(p => p > 0f).Average();
                }
                catch
                {
                    return 0f;
                }
            }
        }

        internal override string ReplaceMarkers(string inString, PackContentCache cache)
        {
            int encounterCount = this.Encounters.Count();
            int regionsCount = this.Regions.Count();
            string encounterString = encounterCount == 1 ? "1 encounter" : $"{encounterCount} encounters";
            string regionString = regionsCount == 1 ? "1 region" : $"{regionsCount} regions";
            string summaryString = $"{regionString} and {encounterString}";
            if (encounterCount == 0 && regionsCount > 0)
                summaryString = regionString;
            if (regionsCount == 0 && encounterCount > 0)
                summaryString = encounterString;
            return base.ReplaceMarkers(inString, cache)
                       .Replace("[encountercount]", encounterString)
                       .Replace("[regioncount]", regionString)
                       .Replace("[summary]", summaryString);
        }

        private static readonly Dictionary<string, string> EncounterMap = new();
        [HarmonyPatch(typeof(EncounterManager), nameof(EncounterManager.Add))]
        [HarmonyPrefix]
        private static void CaptureEncounterModGuid(EncounterBlueprintData newEncounter)
        {
            Assembly callingAssembly = Assembly.GetCallingAssembly();
            string modGuid = Extensions.GetModIdFromCallstack(callingAssembly);
            if (!string.IsNullOrEmpty(modGuid))
                EncounterMap[newEncounter.name] = modGuid;
        }
    }
}