using System.Linq;
using InscryptionAPI.Card;
using DiskCardGame;
using BepInEx.Bootstrap;
using System.Collections.Generic;
using System;
using UnityEngine;
using Infiniscryption.PackManagement.UserInterface;

namespace Infiniscryption.PackManagement
{
    public class PackInfo : PackInfoBase
    {
        public enum PackMetacategory
        {
            LeshyPack = 0,
            P03Pack = 1,
            GrimoraPack = 2,
            MagnificusPack = 3
        }

        public static PackMetacategory GetTempleDefaultMetacategory(CardTemple temple)
        {
            switch (temple)
            {
                case CardTemple.Nature:
                    return PackMetacategory.LeshyPack;
                case CardTemple.Tech:
                    return PackMetacategory.P03Pack;
                case CardTemple.Undead:
                    return PackMetacategory.GrimoraPack;
                case CardTemple.Wizard:
                    return PackMetacategory.MagnificusPack;
                default:
                    return PackMetacategory.LeshyPack;
            }
        }

        public const string JSONLOADER = "MADH.inscryption.JSONLoader";
        public const string TEMPLEINDICATOR = "DiskCardGame.CardTemple.";
        public const string LEFTOVERSINDICATOR = "PackManager.Leftovers";

        internal PackInfo(bool leftovers) : base(leftovers) { }
        internal PackInfo(CardTemple temple) : base(temple) { }
        internal PackInfo(string modPrefix) : base(modPrefix) { }
        internal PackInfo(string modPrefix, PackMetacategory category) : base(modPrefix)
        {
            this.ValidFor = new() { category };
        }

        protected override void TryInitializeImpl()
        {
            List<CardInfo> cards = Cards.ToList();
            if (cards != null && cards.Count > 0)
            {
                // Build the title
                string modGuid = cards[0].GetModTag();
                if (!string.IsNullOrEmpty(modGuid) &&
                    !modGuid.Equals(JSONLOADER, System.StringComparison.OrdinalIgnoreCase) &&
                    Chainloader.PluginInfos.ContainsKey(modGuid))
                {
                    var modInfo = Chainloader.PluginInfos[modGuid];
                    AutoGeneratedTitle = modInfo.Metadata.Name;
                }
                else
                {
                    AutoGeneratedTitle = $"Card Pack: {this.ModPrefix}";
                }

                // Build the description
                int cardsToList = Math.Min(7, cards.Count);
                AutoGeneratedDescription = $"Cards in this pack: {string.Join(", ", cards.Take(cardsToList).Select(ci => ci.DisplayedNameLocalized))} and {cards.Count - 7} other{(cards.Count - 7 > 1 ? "s" : String.Empty)}.";
            }
        }

        internal override bool SetOfPacksIsValid(List<PackInfoBase> packs, PackContentCache cache)
        {
            return packs.Where(p => cache.GetContentsOfPack(p).Count() > 0).Count() > 0;
        }

        public IEnumerable<CardInfo> Cards
        {
            get
            {
                if (IsBaseGameCardPack)
                    return CardManager.AllCardsCopy.Where(ci => ci.IsBaseGameCard() && ci.temple == this.DefaultPackTemple);
                else if (IsStandardCardPack)
                    return CardManager.AllCardsCopy.Where(ci => this.ModPrefix.Equals(ci.GetModPrefix()));
                else
                {
                    // Get all currently defined packs from the pack manager:
                    List<string> allKnownPrefixes = PackManager.AllPacks<PackInfo>().Where(pi => pi.IsStandardCardPack).Select(pi => pi.ModPrefix).ToList();
                    return CardManager.AllCardsCopy.Where(ci => !ci.IsBaseGameCard() && !allKnownPrefixes.Contains(ci.GetModPrefix()));
                }
            }
        }

        public override IEnumerable<string> PackContents => Cards.Select(c => c.name);

        public override IEnumerable<string> ScreenFilteredContents => Cards.Where(ci => ci.CardIsValidForScreenState()).Select(ci => ci.name);

        public override string Key
        {
            get
            {
                if (this.IsBaseGameCardPack)
                    return $"{TEMPLEINDICATOR}{this.DefaultPackTemple.Value.ToString()}";

                if (this.IsLeftoversPack)
                    return LEFTOVERSINDICATOR;

                return this.ModPrefix;
            }
        }

        public override CardInfo IconCard
        {
            get
            {
                int maxPowerLevel = 0;
                CardInfo maxCard = null;
                List<string> contentCache = PackContents.ToList();
                foreach (CardInfo card in CardManager.AllCardsCopy.Where(ci => contentCache.Contains(ci.name)))
                {
                    if (card.PowerLevel > maxPowerLevel)
                    {
                        maxPowerLevel = card.PowerLevel;
                        maxCard = card;
                    }
                }
                return maxCard;
            }
        }

        public override float PowerLevel
        {
            get
            {
                var names = ScreenFilteredContents.ToList();
                try
                {
                    return (float)CardManager.AllCardsCopy.Where(ci => names.Contains(ci.name)).Where(ci => ci != null).Select(ci => ci.PowerLevel).Average();
                }
                catch
                {
                    return 0f;
                }
            }
        }

        private string RandomCardName(List<string> cards) => CardManager.AllCardsCopy.CardByName(cards[UnityEngine.Random.Range(0, cards.Count)])?.DisplayedNameLocalized ?? "";

        private string ReplaceRandom(string text, PackContentCache cache)
        {
            List<string> cards = cache.GetContentsOfPack(this);
            while (true)
            {
                int pos = text.IndexOf("[randomcard]");
                if (pos < 0)
                    return text;

                text = text.Substring(0, pos) + RandomCardName(cards) + text.Substring(pos + 12);
            }
        }

        internal override string ReplaceMarkers(string inString, PackContentCache cache)
        {
            return ReplaceRandom(base.ReplaceMarkers(inString, cache), cache);
        }
    }
}