using System;
using System.Collections.Generic;
using DiskCardGame;
using Infiniscryption.PackManagement.UserInterface;
using UnityEngine;
using static Infiniscryption.PackManagement.PackInfo;

namespace Infiniscryption.PackManagement
{
    public abstract class PackInfoBase
    {
        /// <summary>
        /// If this pack represents content from the base game, this tells you which act of the game the content is for
        /// </summary>
        public CardTemple? DefaultPackTemple { get; protected set; }

        /// <summary>
        /// The prefix that will be used to filter content that is considered part of this pack.
        /// </summary>
        public string ModPrefix { get; protected set; }

        /// <summary>
        /// If true, the contents of this pack can span multiple scrybe mods/game acts. If false, *all* content will be forced to be playable in whichever act the pack is marked valid for.
        /// </summary>
        public bool SplitPackByCardTemple { get; set; } = false;

        /// <summary>
        /// A "leftovers" pack represents all stray content found in the game that doesn't belong to any other pack.
        /// </summary>
        public bool IsLeftoversPack { get; protected set; }

        /// <summary>
        /// Indicates if this pack represents content from the base game
        /// </summary>
        public bool IsBaseGameCardPack => DefaultPackTemple.HasValue;

        /// <summary>
        /// Indicates if this pack represents mod-added content
        /// </summary>
        public bool IsStandardCardPack => !DefaultPackTemple.HasValue && !IsLeftoversPack;

        protected bool initialized { get; private set; } = false;

        protected PackInfoBase()
        {
        }

        internal PackInfoBase(CardTemple temple)
        {
            this.DefaultPackTemple = temple;
            this.ValidFor = new List<PackMetacategory>() { GetTempleDefaultMetacategory(temple) };
        }

        internal PackInfoBase(string modPrefix)
        {
            this.ModPrefix = modPrefix;
            this.ValidFor = new() { PackMetacategory.P03Pack, PackMetacategory.LeshyPack, PackMetacategory.MagnificusPack, PackMetacategory.GrimoraPack };
        }

        internal PackInfoBase(bool leftovers)
        {
            // Why this instead of an internal default constructor? 
            // To prevent any weird edge cases where someone is using reflection improperly and
            // creates a pack using a default contructor without realizing what that would mean
            if (!leftovers)
                throw new InvalidOperationException("Can only use bool constructor if bool is true.");

            // This creates the "leftovers" pack
            IsLeftoversPack = leftovers;
            this.ValidFor = new() { PackMetacategory.GrimoraPack, PackMetacategory.MagnificusPack,
                                     PackMetacategory.P03Pack, PackMetacategory.LeshyPack };
        }

        protected void TryInitialize()
        {
            if (initialized)
                return;

            TryInitializeImpl();
        }

        protected abstract void TryInitializeImpl();

        private string _title;
        protected string AutoGeneratedTitle;

        /// <summary>
        /// The title displayed when this pack is select on the pack management screen.
        /// </summary>
        public virtual string Title
        {
            get
            {
                if (!string.IsNullOrEmpty(_title))
                    return Localization.Translate(_title);

                if (!initialized)
                    TryInitialize();

                return Localization.Translate(AutoGeneratedTitle);
            }
            set { _title = value; }
        }

        private string _description;
        protected string AutoGeneratedDescription;

        /// <summary>
        /// The description displayed when the pack is selected on the pack management screen
        /// </summary>
        public string Description
        {
            get
            {
                if (!string.IsNullOrEmpty(_description))
                    return Localization.Translate(_description);

                if (!initialized)
                    TryInitialize();

                return Localization.Translate(AutoGeneratedDescription);

            }
            set { _description = value; }
        }

        /// <summary>
        /// The art shown for this pack on the pack management screen
        /// </summary> 
        public virtual Sprite PackArt { get; protected set; }

        /// <summary>
        /// Indicates which scrybe mods this pack should be valid for.
        /// </summary>
        public List<PackMetacategory> ValidFor { get; set; }

        /// <summary>
        /// Sets the pack art for this pack
        /// </summary>
        /// <param name="t">A 46x74 pixel texture</param>
        public void SetTexture(Texture2D t)
        {
            t.filterMode = FilterMode.Point;
            this.PackArt = Sprite.Create(t, new Rect(0f, 0f, 46f, 74f), new Vector2(0.5f, 0.5f));
            this.PackArt.name = t.name + "_sprite";
        }

        /// <summary>
        /// Gets the contents of this pack
        /// </summary>
        public abstract IEnumerable<string> PackContents { get; }

        /// <summary>
        /// Gets the contents of this pack that are valid for the current screen state
        /// </summary>
        /// <remarks>Not everything in a pack is actually valid. For example, you might
        /// have a card in a pack that is not acquirable; this enumeration would filter
        /// that out</remarks>
        public virtual IEnumerable<string> ScreenFilteredContents => PackContents;

        /// <summary>
        /// The unique identifier for this pack
        /// </summary>
        public abstract string Key { get; }

        /// <summary>
        /// A card that is used to represent this pack if there is no pack art
        /// </summary>
        public abstract CardInfo IconCard { get; }

        /// <summary>
        /// A representation of the overall power level/difficulty of this pack
        /// </summary>
        public abstract float PowerLevel { get; }

        internal abstract bool SetOfPacksIsValid(List<PackInfoBase> packs, PackContentCache cache);

        internal virtual string ReplaceMarkers(string inString, PackContentCache cache)
        {
            return (inString ?? "").Replace("[count]", cache.GetContentsOfPack(this).Count.ToString())
                           .Replace("[name]", this.Title)
                           .Replace("[powerlevel]", Math.Round(cache.GetPowerLevel(this), 2).ToString());
        }
    }
}